version: "3.9"
services:
  mongodb:
    image: mongo:latest
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongodb.env
    ports:
      - '27017:27017'
    container_name: mongodb-container
    #networks:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
    container_name: backend-container
  frontend:
    build: ./frontend
    env_file:
      - ./env/frontend.env
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - backend
    volumes: 
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./conf/:/etc/nginx/conf.d/:ro
    container_name: frontend-container
    restart: always
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
volumes:
  data: