version: "3.9"
services:
  mongodb:
    image: mongo:latest
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongodb.env
    ports:
      - '27017:27017'
    container_name: mongodb-container
    #networks:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
    container_name: backend-container
  frontend:
    build: ./frontend
    env_file:
      - ./env/frontend.env
    ports:
      - '80:80'
    depends_on:
      - backend
    container_name: frontend-container

volumes:
  data: